---
title: "Practice Assigment 3 Coding with R"
author: "Juan Lozano"
date: "June 27, 2018"
output: html_document
---


## Week 4 Practice Assigment 

Finding the best hospital in a state

```{r}
best <-function(state, colname){
  
  outcome <-read.csv("Assigment3/outcome-of-care-measures.csv", colClasses = "character")
  names(outcome)[11]<-"heart attack"
  names(outcome)[17]<-"heart failure"
  names(outcome)[23]<-"pneumonia"
  
                 if (colname %in% colnames(outcome) ==FALSE){
                   stop(message("invalid outcome"))
                 } else if (!state %in% outcome$State ==TRUE){
                   stop(message("invalid state"))
                 } else {
                   temp <- subset(outcome, State ==state, select=c(Hospital.Name, get(colname)))
                   temp1 <- suppressWarnings(subset(temp, !is.na(as.numeric(temp[,2]))))
                   temp2 <- temp1[which.min(temp1[[colname]]),]
                   temp2[,1]
                 }
}
```
Ranking hospitals by outcome in a state

```{r}
rankhospital <-function(state, colname, num = "best"){
  
  outcome <-read.csv("Assigment3/outcome-of-care-measures.csv", colClasses = "character")
  names(outcome)[11]<-"heart attack"
  names(outcome)[17]<-"heart failure"
  names(outcome)[23]<-"pneumonia"
  
  if (colname %in% colnames(outcome) ==FALSE){
    stop(message("invalid outcome"))
  } else if (!state %in% outcome$State ==TRUE){
    stop(message("invalid state"))
  } else {
    temp <- subset(outcome, State ==state, select=c(Hospital.Name, get(colname)))
    temp1 <- suppressWarnings(subset(temp, !is.na(as.numeric(temp[,2]))))
    temp2 <- temp1[order(as.numeric(temp1[[colname]]),temp1$Hospital.Name),]
    
    
    if (num == "worst"){
      temp2[nrow(temp2) ,1]
    } else if (num == "best"){
      temp2[1,1]
    } else {
      temp2[num,1]
    }

    }
}
```
Ranking hospitals in all states

```{r}
rankall <-function(colname, num = "best"){
  
  outcome <-read.csv("Assigment3/outcome-of-care-measures.csv", colClasses = "character")
  names(outcome)[11]<-"heart attack"
  names(outcome)[17]<-"heart failure"
  names(outcome)[23]<-"pneumonia"
  
  if (colname %in% colnames(outcome) ==FALSE){
    stop(message("invalid outcome"))
  } else {
    
    temp1 <- suppressWarnings(outcome[order(outcome$State, as.numeric(outcome[[colname]]), outcome$Hospital.Name),])
    states<- unique(temp1[,7])
    result <- data.frame(matrix(ncol = 3, nrow = 0))
    x <- c("Hospital.Name", "heart attack", "State")
    colnames(result) <- x
   
    
    if (num == "worst"){
      for (i in 1:length(states)){
        resulttest <- temp1[temp1$State %in% states[i],]
        resulttest1<- subset(resulttest, select=c("Hospital.Name", colname, "State"))
        result[i,] <-suppressWarnings(resulttest1[which.max(resulttest1[[colname]]),])
        
      }
   
      
      
    } else if (num == "best"){
      for (i in 1:length(states)){
        resulttest <- temp1[temp1$State %in% states[i],]
        resulttest1<- subset(resulttest, select=c("Hospital.Name", colname, "State"))
        result[i,] <-resulttest1[1,]
        
      }
    } else {
      for (i in 1:length(states)){
        resulttest <- temp1[temp1$State %in% states[i],]
        resulttest1<- subset(resulttest, select=c("Hospital.Name", colname, "State"))
        result[i,] <-resulttest1[num,]
        
      }
     
    }
    
  }
  result
}
```
